
services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php
        volumes:
            - .:/var/www/html
        expose:
            - "9000"
        depends_on:
            - mysql

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_app
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html:ro
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - php

volumes:
    mysql_data:

